export default {
  //字段类型: 决定渲染组件
  type: {
    id: 1,
    type: "select",
    code: "type",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "组件类型",
    placeholder: "请选择字段组件类型",
    required: true,
    isFull: false,
    desc: "字段组件类型",
    multiple: null,
    options: [
      {
        label: "输入框-input",
        value: "input"
      },
      {
        label: "文本框-textarea",
        value: "textarea"
      },
      {
        label: "下拉框-select",
        value: "select"
      },
      {
        label: "开关-switch",
        value: "switch"
      },
      {
        label: "单选-radio",
        value: "radio"
      },
      {
        label: "多选-checkbox",
        value: "checkbox"
      },
      {
        label: "日期-date",
        value: "date"
      },
      {
        label: "日期时间-datetime",
        value: "datetime"
      },
      {
        label: "年-year",
        value: "year"
      },
      {
        label: "年月-month",
        value: "month"
      },
      {
        label: "周-week",
        value: "week"
      },
      {
        label: "日期多选-dates",
        value: "dates"
      },
      {
        label: "日期范围-daterange",
        value: "daterange"
      },
      {
        label: "时间-time",
        value: "time"
      },
      {
        label: "时间范围-timerange",
        value: "timerange"
      }
    ],
    filterable: true,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  code: {
    id: 2,
    type: "input",
    code: "code",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "字段code",
    placeholder: "请输入字段code",
    required: true,
    isFull: false,
    desc: "字段code,用于字段的唯一标识",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  //渲染类型
  renderType: {
    id: 3,
    type: "select",
    code: "renderType",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "渲染类型",
    placeholder: "请选择字段渲染类型",
    required: true,
    isFull: false,
    desc: "字段渲染类型",
    multiple: null,
    options: [
      {
        label: "输入型-form",
        value: "form"
      },
      {
        label: "显示型-table",
        value: "table"
      }
    ],
    filterable: false,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  isShow: {
    id: 4,
    type: "switch",
    code: "isShow",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否显示",
    placeholder: "请选择是否显示",
    required: true,
    isFull: false,
    desc: "字段是否显示",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  disabled: {
    id: 5,
    type: "switch",
    code: "disabled",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否只读",
    placeholder: "请选择是否只读",
    required: true,
    isFull: false,
    desc: "字段是否只读",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  label: {
    id: 6,
    type: "input",
    code: "label",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "字段label",
    placeholder: "请输入字段label",
    required: true,
    isFull: false,
    desc: "字段label",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  placeholder: {
    id: 7,
    type: "input",
    code: "placeholder",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "字段placeholder",
    placeholder: "请输入字段placeholder",
    required: true,
    isFull: false,
    desc: "字段placeholder",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  required: {
    id: 8,
    type: "switch",
    code: "required",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否必填",
    placeholder: "请选择是否必填",
    required: true,
    isFull: false,
    desc: "字段是否必填",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  isFull: {
    id: 9,
    type: "switch",
    code: "isFull",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否整行显示",
    placeholder: "请选择是否整行显示",
    required: true,
    isFull: false,
    desc: "字段是否整行显示",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  desc: {
    id: 10,
    type: "textarea",
    code: "desc",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "字段描述",
    placeholder: "请输入字段描述",
    required: false,
    isFull: true,
    desc: "字段描述",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
// 受视图条件影响字段
  multiple: {
    id: 11,
    type: "switch",
    code: "multiple",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否多选",
    placeholder: "请选择是否多选",
    required: true,
    isFull: false,
    desc: "字段是否多选",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  filterable: {
    id: 12,
    type: "switch",
    code: "filterable",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否可搜索",
    placeholder: "请选择是否可搜索",
    required: true,
    isFull: false,
    desc: "字段是否可搜索",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  showChooseAll: {
    id: 13,
    type: "switch",
    code: "showChooseAll",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "是否显示全选",
    placeholder: "请选择是否显示全选",
    required: true,
    isFull: false,
    desc: "字段是否显示全选",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  start: {
    id: 14,
    type: "datetime",
    code: "start",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "起始日期/时间",
    placeholder: "请选择起始日期/时间",
    required: false,
    isFull: false,
    desc: "字段选择范围的起始日期/时间",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  end: {
    id: 14,
    type: "datetime",
    code: "end",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "结束日期/时间",
    placeholder: "请选择结束日期/时间",
    required: false,
    isFull: false,
    desc: "字段选择范围的结束日期/时间",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
  defaultValue: {
    id: 15,
    type: "input",
    code: "defaultValue",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "默认值",
    placeholder: "请输入默认值",
    required: false,
    isFull: false,
    desc: "字段的默认值",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },

  //options批量表的字段value
  value: {
    id: 16,
    type: "input",
    code: "value",
    renderType: "form",
    isShow: true,
    disabled: false,
    label: "选项真实值",
    placeholder: "请输入选项真实值",
    required: true,
    isFull: false,
    desc: "选项真实值",
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null
  },
};