export default {
  //字段类型: 决定渲染组件
  type: {
    id: 1,
    type: 'select',
    code: 'type',
    renderType: 'form',
    isShow: true,
    disabled: false,
    label: '渲染类型',
    placeholder: '请选择字段渲染类型',
    required: true,
    isFull: false,
    desc: '字段渲染类型',
    multiple: null,
    options: [{
      label: '输入框-input',
      value: 'input',
    }, {
      label: '文本框-textarea',
      value: 'textarea',
    }, {
      label: '下拉框-select',
      value: 'select',
    }, {
      label: '开关-switch',
      value: 'switch',
    }, {
      label: '单选-radio',
      value: 'radio',
    }, {
      label: '多选-checkbox',
      value: 'checkbox',
    }, {
      label: '日期-date',
      value: 'date',
    }, {
      label: '日期时间-datetime',
      value: 'datetime',
    }, {
      label: '年-year',
      value: 'year',
    }, {
      label: '年月-month',
      value: 'month',
    }, {
      label: '周-week',
      value: 'week',
    }, {
      label: '日期多选-dates',
      value: 'dates',
    }, {
      label: '日期范围-daterange',
      value: 'daterange',
    }, {
      label: '时间-time',
      value: 'time',
    }, {
      label: '时间范围-timerange',
      value: 'timerange',
    }, ],
    filterable: true,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null,
  },
  code: {
    id: 2,
    type: 'input',
    code: 'code',
    renderType: 'form',
    isShow: true,
    disabled: false,
    label: '字段code',
    placeholder: '请输入字段code',
    required: true,
    isFull: false,
    desc: '字段code,用于字段的唯一标识',
    multiple: null,
    options: null,
    filterable: null,
    loading: false,
    remote: false,
    start: null,
    end: null,
    rows: null,
    showChooseAll: null,
    defaultValue: null,
  },
  
}