export default {
  type: null,
  code: null,
  // renderType: null,
  // isShow: null,
  // disabled: null,
  // label: null,
  // placeholder: null,
  // required: null,
  // isFull: null,
  // desc: null,
  // multiple: null,
  // options: null,
  // filterable: null,
  // loading: null,
  // remote: null,
  // start: null,
  // end: null,
  // rows: null,
  // showChooseAll: null,
  // defaultValue: null,
}